### ISSUE TITLE
Setup CI in downstream repos

### ISSUE THREAD

**Issue by RileyEv** [bank-manager/stack-snapshots#14]
```[tasklist]
### Tasks
- [ ] https://github.com/bank-manager/stack-snapshots/issues/15
- [ ] https://github.com/bank-manager/stack-snapshots/issues/16
- [ ] https://github.com/bank-manager/stack-snapshots/issues/17
- [ ] https://github.com/bank-manager/stack-snapshots/issues/18
```
